# Generated by Django 5.1.6 on 2025-02-11 21:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("identifier", models.AutoField(primary_key=True, serialize=False)),
                (
                    "first_name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Имя должно содержать только буквы",
                                regex="^[A-Za-zА-Яа-яЁё]+$",
                            )
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Фамилия должна содержать только буквы",
                                regex="^[A-Za-zА-Яа-яЁё]+$",
                            )
                        ],
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Отчество должно содержать только буквы",
                                regex="^[A-Za-zА-Яа-яЁё]+$",
                            )
                        ],
                    ),
                ),
                ("position", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Неверный формат телефона",
                                regex="^+7 (d{3}) d{3}-d{2}-d{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "tg",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Неверный формат Telegram никнейма",
                                regex="^@([A-Za-z]+[_.-]?)+$",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("identifier", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.supplier"
                    ),
                ),
            ],
        ),
    ]
