# Generated by Django 5.1.6 on 2025-02-11 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Неверный формат телефона. Пример: +7 (123) 456-78-90",
                        regex="^+7 (d{3}) d{3}-d{2}-d{2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="tg",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Неверный формат Telegram никнейма. Никнейм должен начинаться с @ и содержать минимум 5 символов.",
                        regex="^@[A-Za-z0-9_]{5,}$",
                    )
                ],
            ),
        ),
    ]
