# Generated by Django 5.1.6 on 2025-02-11 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_supplier_phone_alter_supplier_tg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Неверный формат телефона. Пример: +7 (123) 456-78-90",
                        regex="^7 (d{3}) d{3}-d{2}-d{2}$",
                    )
                ],
            ),
        ),
    ]
