# Generated by Django 5.1.6 on 2025-02-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_categorylevel1_categorylevel2_categorylevel3_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="source_type",
        ),
        migrations.AddField(
            model_name="message",
            name="sourcetype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Блоги", "Блоги"),
                    ("Видео", "Видео"),
                    ("Мессенджеры каналы", "Мессенджеры каналы"),
                    ("Мессенджеры чаты", "Мессенджеры чаты"),
                    ("Микроблоги", "Микроблоги"),
                    ("Онлайн-СМИ", "Онлайн-СМИ"),
                    ("Соцсети", "Соцсети"),
                    ("Форумы", "Форумы"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="categorylevel4",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="message",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="messages", to="polls.categorylevel4"
            ),
        ),
        migrations.DeleteModel(
            name="SourceType",
        ),
    ]
