# Generated by Django 5.1.6 on 2025-02-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_remove_message_source_type_message_sourcetype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="categories",
            field=models.ManyToManyField(
                help_text="Выберите классификацию/ии сообщения",
                to="polls.categorylevel4",
            ),
        ),
    ]
