# Generated by Django 5.1.6 on 2025-02-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_categorylevel_delete_categorylevel3"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryLvl",
            fields=[
                ("identifier", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="CategoryLevel",
        ),
        migrations.DeleteModel(
            name="CategoryLevel1",
        ),
        migrations.DeleteModel(
            name="CategoryLevel2",
        ),
        migrations.DeleteModel(
            name="CategoryLevel4",
        ),
        migrations.AlterField(
            model_name="message",
            name="categories",
            field=models.ManyToManyField(
                help_text="Выберите классификацию/ии сообщения", to="polls.categorylvl"
            ),
        ),
    ]
