# Generated by Django 5.2 on 2025-04-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0011_category_subcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="id",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="id",
        ),
        migrations.AddField(
            model_name="category",
            name="identifier",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="identifier",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
