# Generated by Django 5.2 on 2025-04-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0012_remove_category_id_remove_subcategory_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="emoji",
            field=models.CharField(default="", max_length=10, verbose_name="Эмодзи"),
        ),
    ]
