# Generated by Django 5.2 on 2025-04-27 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0013_category_emoji"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                ("identifier", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessedData",
            fields=[
                ("identifier", models.AutoField(primary_key=True, serialize=False)),
                ("original_text", models.TextField()),
                ("category", models.CharField(max_length=255)),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.uploadedfile",
                    ),
                ),
            ],
        ),
    ]
